from lib import *
print()
Menu  = estudiante("Matricula","Nombre ","Apellido ", "Edad")
alum1 = estudiante("601049   ","Zaira   ","Frine   ", "35  ")
alum3 = estudiante("100738   ","Victor  ","Garcia  ", "20  ")
alum4 = estudiante("100744   ","Diego   ","Lopez   ", "18  ")
alum5 = estudiante("100692   ","Evelyn  ","Lopez   ", "20  ")
alum6 = estudiante("099999   ","Daniel  ","Rojas   ", "20  ")
alum7 = estudiante("100870   ","Maurizio","Rosas   ", "20  ")
alum8 = estudiante("100437   ","Annibal ","Villegas", "20  ")

print("\t CALIFICACIONES \t")
print(Menu)
print("--------------------------------------------------------------")
print(alum1)
print(alum3)
print(alum4)
print(alum5)
print(alum6)
print(alum7)
print(alum8)

print()